### ISSUE TITLE
Add debug logging to list files cleaned / processed

### ISSUE THREAD

**Issue by aportagain** [metocean/vacuum#12]
I think this would be nice to have to easily check everything's working "as expected" when either setting up new configurations or debugging existing ones. E.g., new scheduler action config, first test manually ("list" command or dry-run), then activate in scheduler workflow but with loglevel debug the first couple of cycles to double-check, then decrease loglevel back to default info if everything looks good. Just because "cleaning up" actions are often a bit scary... :)

**Comment by AndreLobato** [comment]
implemented by 9c01507
